### ISSUE TITLE
Error Occurs when Deploying CF  using Window Stemcell

### ISSUE THREAD

**Issue by JY-Lee** [cloudfoundry-attic/cf-release#1279]
I am trying to 1.**deploy BOSH in Ubuntu Environment**,  2. **upload windows2012R2 stemcell & to-be-installed release to the deployed BOSH VM**,  3. **and then deploy CF**.

However,an error occurs on package compile stage of Cloud Foundry, such as go, postres, etc . I suppose the package compiling issue arose as the commands differ in Operating Systems.  

The Manifest below is an example.

```
resource_pools:
- cloud_properties:
    instance_type: Standard_A1
  env:
    bosh:
      password: "<redacted>"
  name: medium
  network: default
  size: 1
  stemcell:
    name: bosh-azure-hyperv-windows2012R2-go_agent
    version: '1200.19'
 
compilation:
  cloud_properties:
    instance_type: Standard_A1
  network: private
  reuse_compilation_vms: true
  workers: 2

networks:
- cloud_properties: {}
  name: public
  type: vip
- name: private
  subnets:
  - cloud_properties:
      subnet_name: snet
      virtual_network_name: vnet
    dns:
    - 8.8.8.8
    gateway: 10.0.1.1
    range: 10.0.1.0/24
    reserved:
    - 10.0.1.1 - 10.0.1.10
    static:
    - 10.0.1.20 - 10.0.1.50
  type: manual

update:
  canaries: 1
  canary_watch_time: 60000
  max_in_flight: 4
  update_watch_time: 60000

jobs:
- instances: 1
  name: scm-manager
  networks:
  - default:
    - dns
    - gateway
    name: private
    static_ips:
    - 10.0.1.30
  - name: public
    static_ips:
    - XXX.XXX.XXX.XXX
  persistent_disk: 10240
  resource_pool: medium
  template: scm-manager

release:
  name: scm-manager
  version: latest

director_uuid: 12aerV3-x......
 
name: scm-manager
```
when you deploy using the Manefest above,

An Error message is printed as below.
```
Task 72

Task 72 | 09:05:33 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 72 | 09:05:33 | Preparing deployment: Preparing deployment (00:00:00)
Task 72 | 09:05:33 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 72 | 09:05:33 | Compiling packages: java8/88ff03b20ad2f59840fbb5f74a074ca8fdc68213
Task 72 | 09:05:33 | Compiling packages: scm-server/594428973e7646710ab7a4ad008f82955836c511 (00:07:03)
Task 72 | 09:15:47 | Compiling packages: java8/88ff03b20ad2f59840fbb5f74a074ca8fdc68213 (00:10:14)
                   L Error: Action Failed get_task: Task b066d3bd-cdf5-4736-679d-aede4a647a4a result: Compiling package java8: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Stderr: + if [[ `uname -a` =~ "x86_64" ]] ; then
+   ~
Missing '(' after 'if' in if statement.
At line:4 char:5
+ if [[ `uname -a` =~ "x86_64" ]] ; then
+     ~
Missing type name after '['.
At line:14 char:3
+ if [[ -f $archive ]] ; then
+   ~
Missing '(' after 'if' in if statement.
At line:14 char:5
+ if [[ -f $archive ]] ; then
+     ~
Missing type name after '['.
At line:24 char:3
+ if [[ ${BOSH_INSTALL_TARGET} ]]; then
+   ~
Missing '(' after 'if' in if statement.
At line:24 char:5
+ if [[ ${BOSH_INSTALL_TARGET} ]]; then
+     ~
Missing type name after '['.
At line:32 char:3
+ if [[ -d bin && `bin/java -version 2>&1` =~ "Java HotSpot" && $? == 0 ]]; 
then
+   ~
Missing '(' after 'if' in if statement.
At line:32 char:5
+ if [[ -d bin && `bin/java -version 2>&1` =~ "Java HotSpot" && $? == 0 ]]; 
then
+     ~
Missing type name after '['.
At line:32 char:14
+ if [[ -d bin && `bin/java -version 2>&1` =~ "Java HotSpot" && $? == 0 ]]; 
then
+              ~~
The token '&&' is not a valid statement separator in this version.
At line:32 char:60
+ if [[ -d bin && `bin/java -version 2>&1` =~ "Java HotSpot" && $? == 0 ]]; 
then
+                                                            ~~
The token '&&' is not a valid statement separator in this version.
Not all parse errors were reported.  Correct the reported errors and try again.
At line:1 char:1
+ iex (get-content -raw packaging)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseExcep 
   tion
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement,Microsoft.Po 
   werShell.Commands.InvokeExpressionCommand

```

**In my understanding, the error message is due to its lack of proper packaging file for the uploaded stemcell environment.
(Since, the error didn't occur when uploaded stemcell was Ubuntu.)

1. I wonder if this issue has ever raised? And if there is any way to solve this kind of compile error?

2. Also, i am curious if the package(which threw the error) is not required to deploy CF in window stemcell.
If so, is it okay to deploy CF after removing all the packages that throws an error?

3. When deploying CF in window, do i need to change script files of the package into windows format ?

4. One more..where can i find guide or documents regarding CF deployment using window stemcell?**

**Comments would be appreciated. Thank you.**
